on:
  push:
    branches:
    - main

permissions:
      id-token: write
      contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3
    # Installs Node and the npm packages saved in your package.json file in the build
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.4.1
      with:
        node-version: 18.x

    - name: install ADF Utilities package
      run: npm install
      # (1) provide the folder location of the package.json file
      working-directory: ${{github.workspace}}/adf-root/build  
        
    - name: Test Directory
      working-directory: ${{github.workspace}}/adf-root/build
      run: |
        ls -la

    # Validates all of the Data Factory resources in the repository. You'll get the same validation errors as when "Validate All" is selected.
    - name: Validate
      run: npm run build validate ${{github.workspace}}/adf-root/ /subscriptions/1ab447f2-70cb-4b4d-bbd2-267bc9607195/resourceGroups/rg-ex-dev01/providers/Microsoft.DataFactory/factories/adf-ex-dev01 
      # (2) The validate command needs the root folder location of your repository where all the objects are stored. And the 2nd parameter is the resourceID of the ADF instance 
      working-directory: ${{github.workspace}}/adf-root/build

    - name: Validate and Generate ARM template
      run: npm run build export ${{github.workspace}}/adf-root/ /subscriptions/1ab447f2-70cb-4b4d-bbd2-267bc9607195/resourceGroups/rg-ex-dev01/providers/Microsoft.DataFactory/factories/adf-ex-dev01  "ExportedArmTemplate"  
      # (3) The build command, as validate, needs the root folder location of your repository where all the objects are stored. And the 2nd parameter is the resourceID of the ADF instance. The 3rd parameter is the exported ARM template artifact name 
      working-directory: ${{github.workspace}}/adf-root/build

      # In order to leverage the artifact in another job, we need to upload it with the upload action 
    - name: upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: ExportedArmTemplate 
        # (4) use the same artifact name you used in the previous export step
        path: ${{github.workspace}}/adf-root/build/ExportedArmTemplate
 
